spring:
  application:
    name: t3ns
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/tens-api
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
