spring:
  application:
    name: t3ns
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/tens-api
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
openai:
  model: "gpt-3.5-turbo"
  api:
    key: ${api_key}
    url: "https://api.openai.com/v1/chat/completions"
