spring:
  application:
    name: t3ns
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/tens-api
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
jwt-secret: 8f09669ab33ae0c90f375f07bca6b22f5ac2a496e505c5ffa3cf15460b69a882